spring.application.name=ms-checkpoint
server.port=8080
server.servlet.context-path=/checkpoint

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

#JIRA integration
jira.url=${JIRA_URL}
jira.email=${JIRA_EMAIL}
jira.api-token=${JIRA_API_TOKEN}

# IA-ENGINE integration
ia-engine.base-url=${AI_ENGINE_BASE_URL}

# Schedulers configuration
schedulers.resumen-actividades.cron=${CRON_RESUMEN_DAILY}
schedulers.notificar-pendientes.cron=${CRON_NOTIFICAR_PENDIENTES}

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# MCP Server
spring.ai.mcp.server.enabled=true

# SPRING MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# SMTP AUTH
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
